version: "3"
services:

  surreal:
    image: surrealdb/surrealdb:1.0.0-beta.9
    restart: always
    ports:
      - "22774:8000"
    command: 
      - start
      - --user=root
      - --pass=root
      - --log=info
