version: "3"
services:

  surreal:
    image: surrealdb/surrealdb:1.0.0-beta.12
    restart: always
    ports:
      - "22773:8000"
    volumes:
      - ./data/surreal:/data
    command: 
      - start
      - --log=info
      - --allow-all

  surreal_beta9:
    image: surrealdb/surrealdb:1.0.0-beta.9
    restart: always
    ports:
      - "22774:8000"
    command: 
      - start
      - --user=root
      - --pass=root
      - --log=info
